amzn/smoke-http

- .gitignore
- .swiftlint.yml
- Sources/QueryCoder/QueryEncoder.swift
- Sources/QueryCoder/QuerySingleValueEncodingContainer.swift
- Sources/SmokeHTTPClient/HTTPClient.swift
- Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift
- Sources/SmokeHTTPClient/HTTPMethod+rawValue.swift
- Sources/SmokeHTTPClient/HTTPRequestInput.swift
*Description of changes:* Code cleanup to fix failures under SwiftLint.
> Code cleanup to conform to SwiftLint rules.

- .travis.yml
- Package.swift
- README.md
- Sources/HTTPPathCoding/Array+getShapeForTemplate.swift
- Sources/ShapeCoding/DecodingErrorExtension.swift
- Sources/ShapeCoding/ShapeDecoder+unbox.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
*Issue #, if available:* #28 
*Description of changes:* Update tools version. Address Swift 5.0 compile warnings.
> Remove pre Swift 5.0 compatibility.

- Package.resolved
- README.md
- Sources/HTTPPathCoding/Array+getShapeForTemplate.swift
- Sources/ShapeCoding/DecodingErrorExtension.swift
- Sources/ShapeCoding/ShapeDecoder+unbox.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
- Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
*Description of changes:* Remove compile warnings under Swift 5.x.
> Remove compile warnings

- Sources/SmokeHTTPClient/MockInvocationTraceContext.swift
*Description of changes:* Code cleanup - remove magic string to variable.
> Code cleanup - remove magic string to variable.

- .travis.yml
- CITests/run
> Fix CI tests.

- .travis.yml
- README.md
- Sources/SmokeHTTPClient/StandardHTTPClientCoreInvocationReporting.swift
*Description of changes:* Add CI tests for Swift 5.2.
> Add Swift 5.2 CI tests.

- .travis.yml
- README.md
*Description of changes:* Update CI to test 5.3.1 with all Linux distributions and 5.2.5 to just a single representative distribution.
> Update CI with 5.3.1.

- Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift
Fix HTTP client retry algorithm according to https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
> Fix HTTP client retry algorithm

- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Issue #, if available:* Allow retries for AsyncHTTPClient.HTTPClientError.remoteConnectionClosed, return them as 500 errors.
> Allow retries for AsyncHTTPClient.HTTPClientError.remoteConnectionClosed

- Sources/SmokeHTTPClient/TestEventLoopProvider.swift
*Description of changes:* Add a test event loop provider for convenience.
> Convenience test event loop provider

- Sources/SmokeHTTPClient/TestEventLoopProvider.swift
*Description of changes:* Add convenience initializers for TestEventLoopProvider.
> Add convenience initializers for TestEventLoopProvider.

- .travis.yml
*Description of changes:* Add CI for Swift 5.4 nightly.
> Add CI for Swift 5.4 nightly.

- .travis.yml
- README.md
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithoutOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithoutOutput.swift
*Description of changes:* Add CI for Swift 5.4.
> Add CI for Swift 5.4.

- .travis.yml
- Package.resolved
- Package.swift
- README.md
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithoutOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithOutput.swift
- Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithoutOutput.swift
*Description of changes:* Use async/await bridge provided by _NIOConcurrency.
> Use async/await bridge provided by _NIOConcurrency.

- .travis.yml
*Description of changes:* Update CI base distribution.
> Update CI base distribution.

- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
Correctly handle errors that occur before a response can be returned (such as connection errors). This will allow tlsHandshakeTimeout and connectTimeout errors to be appropriately retried.
Verified by locally modifying `async-http-client` to consistently return these errors.
> Correctly handle errors that occur before a response can be returned.

- Package.resolved
- Package.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Description of changes:* Add the ability to pass in the ConnectionPool configuration. Doesn't change the default configuration.
> Configurable connection pool

- .github/workflows/swift.yml
- README.md
> Update CI for 5.6, removing 5.3.

- Package.resolved
- Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Description of changes:* Lower log level from debug to trace.
> Lower log level from debug to trace.

- .github/workflows/swift.yml
- README.md
*Description of changes:* Add CI for 5.7, drop 5.4.
> Add CI for 5.7, drop 5.4.

- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Description of changes:* Pass the per-request logger into AHC when enableAHCLogging = true.
> Pass the per-request logger into AHC when enableAHCLogging = true.

- Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Description of changes:* Adds a span for the retry block and for each request made.
> Add spans for client retries and individual attempts.

- Sources/SmokeHTTPClient/HTTPOperationsClient.swift
*Description of changes:* Disable client spans due to performance investigation.
> Disable client spans due to performance investigation.

- README.md
None
Enhance README.md for adding 'swift' to the code block.
> Enhance README.md for adding 'swift' to the code block.
