amzn/smoke-http

Sources/ShapeCoding/DateISO8601Extensions.swift
Sources/ShapeCoding/DecodingErrorExtension.swift
Sources/ShapeCoding/ShapeCodingKey.swift
Sources/ShapeCoding/ShapeDecoder+unbox.swift
Sources/ShapeCoding/ShapeDecoder.swift
Sources/ShapeCoding/ShapeDecoderDelegate.swift
Sources/ShapeCoding/ShapeKeyedDecodingContainer+KeyedDecodingContainerProtocol.swift
Sources/ShapeCoding/ShapeKeyedDecodingContainer.swift
Sources/ShapeCoding/ShapeUnkeyedDecodingContainer.swift

*Issue #, if available:* #6 and #1 
*Description of changes:* Add a Shape Decoder in the ShapeCoding package that provides a generic decoder that can be shared across different Codable decoders for query strings, headers and path tokens.
*Testing performed:* Along with other changes that I will submit for future PRs, I have verified encoders and decoders for query strings, http headers and http paths using these classes. These will have further unit tests.

Add a generic Shape decoder

---

Sources/ShapeCoding/ShapeDecoder.swift
Sources/ShapeCoding/ShapeDecoderDelegate.swift
Sources/ShapeCoding/ShapeElement.swift
Sources/ShapeCoding/ShapeKeyedEncodingContainer.swift
Sources/ShapeCoding/ShapeSingleValueEncodingContainer.swift
Sources/ShapeCoding/ShapeSingleValueEncodingContainerDelegate.swift
Sources/ShapeCoding/ShapeUnkeyedEncodingContainer.swift

*Issue #, if available:* #5 and #6 
*Description of changes:* Add a Shape Encoder in the ShapeCoding package that provides a generic decoder that can be shared across different Codable decoders for query strings, headers and path tokens.
*Testing performed:* Along with other changes that I will submit for future PRs, I have verified encoders and decoders for query strings, http headers and http paths using these classes. These will have further unit tests.

Add a generic Shape encoder

---

Sources/HTTPPathCoding/HTTPPathDecoder.swift
Sources/HTTPPathCoding/HTTPPathSegment.swift
Sources/HTTPPathCoding/HTTPPathToken.swift
Tests/HTTPPathCodingTests/HTTPPathEncoderTests.swift
Tests/HTTPPathCodingTests/HTTPPathSegmentTests.swift

*Description of changes:* Add the ability to handle a trail beyond a greedy token. An example of this kind of path-
```
items{firstly}/things/{secondly}/{thirdly+}?tail
```
Add additional tests for http path encoder/decoder.

Add the ability to handle a tail beyond a greedy token

---

.swiftlint.yml
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift
Sources/SmokeHTTPClient/HTTPClientDelegate.swift
Sources/SmokeHTTPClient/HTTPRequestInputProtocol.swift
Sources/SmokeHTTPClient/HTTPResponseComponents.swift
Sources/SmokeHTTPClient/HTTPResponseOutputProtocol.swift

*Issue #, if available:* #2 and #3
* clean up HTTPClient by splitting into multiple files with extensions for the different APIs
* change the response conformance for the HTTPClient APIs from Decodable to a new protocol HTTPResponseInputProtocol that is equivalent to HTTPRequestInputProtocol but for responses. 
* expose the response headers to the HTTPClientDelegate to it can incorporate them into the response
* allow for empty body responses

HTTPResponseOutputProtocol for responses

---

README.md
Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientDelegate.swift

Allow http requests by returning an optional TLSConfiguration in the HTTPClientDelegate.
*Description of changes:* Allow the HTTPClient to be used in situations where SSL transport is not required. Implemented this by making the TLSConfiguration returned by the HTTPClientDelegate optional and using the correct url scheme and adding the SSLHandler to the channel pipeline based on this.

Allow http requests

---

Package.resolved
Sources/HTTPPathCoding/Array+getShapeForTemplate.swift
Sources/HTTPPathCoding/HTTPPathDecoder.swift
Sources/HTTPPathCoding/HTTPPathSegment.swift
Sources/HTTPPathCoding/HTTPPathToken.swift
Tests/HTTPPathCodingTests/GetShapeForTemplateTests.swift
Tests/LinuxMain.swift

Move logic to get a Shape related to a template from a Path into a common function with case insensitive comparison. This logic is required for both the HTTPPathDecoder and higher level routing/handler selection. 
*Description of changes:* Added unit tests to verify new functionality.

Get a Shape related to a template from a Path

---

Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift

*Description of changes:* Add functions to HTTPClient that accept a RetryConfiguration and handle automatically retrying a request on failure.

Request retry with exponential backoff

---

Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift

Pass a function into the HTTPClient retryable functions to indicate if the error returned is retryable.

On retry requests if a retryable error is returned

---

Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift

* Fixed an issue where async retries where both initiating a retry request and calling the completion handler
* Fixed an issue where retry intervals where not being calculated correctly.
*Testing performed:*
* Verified using a failing async request that retries occurred correctly.

Fixed two issues with exponential retries.

---

Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift

*Description of changes:* Fixed for a fatal error when the retry configuration as 0 as the upper bound retry duration.

Fixed for a fatal error in retry logic

---

Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift

*Description of changes:* Avoid modulus by zero in the Linux branch of getRetryInterval().

Fix crash on Linux branch of getRetryInterval().

---

Sources/ShapeCoding/RawShape.swift
Sources/ShapeCoding/ShapeElement.swift
Sources/ShapeCoding/ShapeSingleValueEncodingContainer.swift
Sources/ShapeCoding/ShapeSingleValueEncodingContainerDelegate.swift
Sources/ShapeCoding/StandardShapeSingleValueEncodingContainerDelegate.swift

*Description of changes:* Add a RawShape enumeration with the ability to extract the original decoded form (string, nested array, nested dictionary from a `ShapeSingleValueEncodingContainer` RawShape conforms to `Codable`, allowing easier interoperability with other encoders/decoders such as JSONDecoder/JSONEncoder.

Add a RawShape enumeration 

---

Sources/HTTPHeadersCoding/HTTPHeadersDecoder.swift
Sources/HTTPHeadersCoding/HTTPHeadersEncoder.swift
Sources/HTTPPathCoding/Array+getShapeForTemplate.swift
Sources/HTTPPathCoding/HTTPPathDecoder.swift
Sources/HTTPPathCoding/HTTPPathEncoder.swift
Sources/QueryCoding/QueryDecoder.swift
Sources/QueryCoding/QueryEncoder.swift
Sources/ShapeCoding/StandardDecodingOptions.swift
Sources/ShapeCoding/StandardEncodingOptions.swift
Sources/ShapeCoding/StandardShapeParser.swift
Sources/ShapeCoding/StandardShapeSingleValueEncodingContainerDelegate.swift
Tests/LinuxMain.swift
Tests/ShapeCodingTests/ShapeSingleValueEncodingContainerTests.swift
Tests/ShapeCodingTests/StandardShapeParserTests.swift

*Issue #, if available:* https://github.com/amzn/smoke-aws/issues/10
*Description of changes:* Add a key transform strategy for encoding and decoding shapes with a passthrough option, an option to capitalise and de-capitalise the first character and a custom transform. This is enable use cases where there is a known mapping from the Codable instance to the serialised form that cannot be fully expressed as CodingKeys (the mapping is different in different circumstances.
*Testing performed:* Added unit tests for encoding and decoding with all three strategy options. Also verified that this enables a fix (with additional changes to SmokeAWS) for https://github.com/amzn/smoke-aws/issues/10 (where encoding for EC2 requires capitalisation of keys but decoding doesn't).
By submitting this pull …

Add a key transform strategy for encoding and decoding shapes.

---

Package.resolved
Package.swift
Sources/ShapeCoding/DateISO8601Extensions.swift
Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift

*Description of changes:* 
* Add reuse socket option as shown here[1]
* Don't use a singleton date formatter as it may retain memory
* Only calculate the TLSConfiguration for a client from its delegate once
* Cleanup response handling with NIOFoundationCompat. 
[1] https://github.com/apple/swift-nio-ssl/blob/master/Sources/NIOHTTP1Client/main.swift#L87
*Description of changes:* Tested in beta environment (Linux). Confirmed functionally correct. Continuing to investigate long term memory performance 

Add reuse socket option and cleanup response handling

---

Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift

* Move state mutation to private functions to reduce the possibility future changes will accidentally break state mutation and locking
* Use a `DispatchGroup` to handle closure waiters for HTTPClient, as described in https://github.com/amzn/smoke-framework/pull/18
* Fix instances of logging response as request
* Clear the HTTPClient body data as soon as possible 
*Testing performed:* Unit tests pass. Tested manually connecting to an AWS service to get back expected response.

Http client state cleanup

---

.gitignore
.travis.yml
CITests/run
README.md

*Description of changes:* Add CI Tests for Swift 5.0.1 under Ubuntu 16.04 and Ubuntu 18.04.

Add CI Tests for Swift 5.0.1 under Ubuntu 16.04 and Ubuntu 18.04

---

.travis.yml
README.md

*Description of changes:* Add CI tests for Swift 5.1. Disabled SwiftLint as it currently doesn't build for Swift 5.1.

Add CI tests for Swift 5.1

---

Package.resolved
Package.swift
Sources/HTTPPathCoding/HTTPPathSegment.swift
Sources/ShapeCoding/RawShape.swift
Sources/ShapeCoding/ShapeKeyedEncodingContainer.swift
Sources/SmokeHTTPClient/BodyHTTPRequestInput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandlerDelegate.swift
Sources/SmokeHTTPClient/HTTPClientDelegate.swift
Sources/SmokeHTTPClient/HTTPClientInnerRetryInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInvocationContext.swift
Sources/SmokeHTTPClient/HTTPClientInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPRequestInput.swift
Sources/SmokeHTTPClient/HttpClientError.swift
Sources/SmokeHTTPClient/StandardHTTPClientInvocationReporting.swift

*Issue #, if available:* #31 #32
*Description of changes:* 
Adopt SwiftMetrics and record invocation metrics for-
* successCounter: Metrics.Counter
* failure5XXCounter: Metrics.Counter
* failure4XXCounter: Metrics.Counter
* retryCountRecorder: Metrics.Recorder
* latencyTimer: Metrics.Timer
Adopt SwiftLog and pass a logger instance for each invocation.

Migrate to swift-log and swift-metrics.

---

.travis.yml

*Description of changes:* Swiftlint 0.36.0 supports Swift 5.1. Enabling Swiftlint on the CI tests for this compiler version.

Swiftlint 0.36.0 supports Swift 5.1.

---

Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandler.swift
Sources/SmokeHTTPClient/HTTPClientChannelInboundHandlerDelegate.swift
Sources/SmokeHTTPClient/HTTPClientDelegate.swift
Sources/SmokeHTTPClient/HTTPClientInnerRetryInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInvocationContext.swift
Sources/SmokeHTTPClient/HTTPClientInvocationReporting.swift
Sources/SmokeHTTPClient/InvocationTraceContext.swift
Sources/SmokeHTTPClient/StandardHTTPClientInvocationReporting.swift

*Description of changes:* Pass through a tracing context type, with the ability for that type to record the start and end of a downstream service call, modify the headers sent on the call and use the headers from the response.

Downstream service call tracing

---

Sources/SmokeHTTPClient/MockInvocationTraceContext.swift

*Description of changes:* Add a MockInvocationTraceContext to use for testing rather than requiring the user to generate one.

Add a MockInvocationTraceContext.

---

Sources/SmokeHTTPClient/MockInvocationTraceContext.swift

*Description of changes:* Add public constructor to MockInvocationTraceContext

Add public constructor to MockInvocationTraceContext

---

Package.resolved
Package.swift

*Description of changes:* Relax version requirements for swift-metrics. Express compatibility with both 1.x and 2.x versions.

Relax version requirements for swift-metrics.

---

Sources/SmokeHTTPClient/HTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInvocationReporting.swift
Sources/SmokeHTTPClient/MockCoreInvocationReporting.swift

Add HTTPClientCoreInvocationReporting protocol and the MockCoreInvocationReporting implementation, replacing equivalents in SmokeAWS, allowing these interfaces to be used without taking a dependency on SmokeAWS.

Add HTTPClientCoreInvocationReporting protocol

---

Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPClient+executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPClientInvocationContext.swift

Provide an outgoingRequestId as Logger metadata to track the same invocation to a client. This will allow log entries for the same entry to be more easily associated through logging.

Provide an outgoingRequestId as Logger metadata 

---

Package.swift
Package@swift-5.0.swift
Package@swift-5.1.swift

*Description of changes:* Update tools version to 5.2. Add legacy manifest files for Swift 5.0 and 5.1.

Update tools version to 5.2. Add legacy manifest files.

---

Sources/SmokeHTTPClient/HTTPClientDelegate.swift

*Issue #, if available:* Supports adding support for non-authenticated calls: https://github.com/amzn/smoke-aws/issues/57
*Description of changes:* Expose the default TLS configuration with a function that isn't a protocol requirement. This allows conforming types of this protocol to override `getTLSConfiguration` while also using the logic for the default configuration if required.

Expose default TLS configuration with non-overridden function.

---

Sources/HTTPHeadersCoding/HTTPHeadersDecoder.swift
Sources/HTTPHeadersCoding/HTTPHeadersEncoder.swift
Sources/HTTPPathCoding/Array+getShapeForTemplate.swift
Sources/HTTPPathCoding/HTTPPathDecoder.swift
Sources/HTTPPathCoding/HTTPPathEncoder.swift
Sources/HTTPPathCoding/HTTPPathToken.swift
Sources/QueryCoding/QueryDecoder.swift
Sources/QueryCoding/QueryEncoder.swift
Sources/ShapeCoding/StandardDecodingOptions.swift
Sources/ShapeCoding/StandardEncodingOptions.swift
Sources/ShapeCoding/StandardShapeDecoderDelegate.swift
Sources/ShapeCoding/StandardShapeSingleValueEncodingContainerDelegate.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift
Tests/QueryCodingTests/QueryEncoderTests.swift
Tests/ShapeCodingTests/ShapeSingleValueEncodingContainerTests.swift
Tests/ShapeCodingTests/StandardShapeParserTests.swift

*Description of changes:* Add ListEncodingStrategy and ListDecodingStrategy.
Required to support the format required by the Cloudformation client.
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateChangeSet.html

Add ListEncodingStrategy and ListDecodingStrategy.

---

Package.resolved
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

Connection timeouts are handled as 400 client errors, which won't get retried by the client.
This change handles connection timeouts as 500 server errors.

Allow retry on connection timeout

---

Sources/SmokeHTTPClient/HTTPClientInvocationDelegate.swift

*Description of changes:* Add public constructor for HTTPRequestParameters. Previously the struct is public, is used in a public protocol but cannot be instantiated outside of the package.

Add public constructor for HTTPRequestParameters.

---

.travis.yml
README.md
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

1. Allow retries on read timeouts.
2. Remove Swift 5.0 CI as that compiler version is now not supported according to the [support policy](https://github.com/amzn/smoke-aws/blob/main/docs/Support_Policy.md).
3. Pass full endpoint to traceContext.handleOutwardsRequestStart.

Allow retries on read timeouts

---

.travis.yml
CITests/run
README.md

*Description of changes:* Add CI tests for CentOS 8, Ubuntu 20.04 and Amazon Linux 2.

Add CI tests for CentOS 8, Ubuntu 20.04 and Amazon Linux 2.

---

Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HttpClientError.swift

*Description of changes:* Fix inconsistency in API signatures. Add isRetriable function to HTTPClientError.
1. Some APIs were still accepting a Swift.Error for their retryOnError handler. Added overloads to create the correct API signature and added a deprecation annotation to the existing signatures.
2. Added isRetriable function to HTTPClientError to support retrying based on the HTTP response code.
Verified, along with related changes in smoke-aws that errors were not being retried incorrectly.

Fix inconsistency in API signatures. Add isRetriable function to HTTPClientError.

---

Package.resolved
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

Default all channel errors to 500 so they can be retried; all client errors as 400 expect read timeout.
*Description of changes:* Default all channel errors to 500 so they can be retried; all client errors as 400 expect read timeout.

Default all channel errors to 500 so they can be retried

---

Sources/SmokeHTTPClient/HTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInnerRetryInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift
Sources/SmokeHTTPClient/StandardHTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/StandardHTTPClientInvocationReporting.swift

*Description of changes:* Add Event loop future returning execute variants.
The added files mirror the existing completion handler based `HTTPOperationsClient +executeAsync*` files and contain the same logic.
Combines with https://github.com/amzn/smoke-framework/pull/67 to pass through the eventloop used by an incoming smoke-framework request to any smoke-http based clients.

Event loop future returning execute variants

---

Package.resolved
Sources/SmokeHTTPClient/HTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInnerRetryInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientInvocationContext.swift
Sources/SmokeHTTPClient/HTTPClientInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/RetriableOutwardsRequestLatencyAggregator.swift
Sources/SmokeHTTPClient/StandardHTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/StandardHTTPClientInvocationReporting.swift

*Description of changes:* Add the ability to aggregate info about output requests.
As mentioned in the code, this is likely going to be able to be standardised when distributed tracing comes along (https://github.com/apple/swift-distributed-tracing) but this provides us with this information until then.
Example log message this allows to be emitted by smoke-framework: 
```
Request completed in 17 milliseconds; 8 milliseconds excluding service calls (there was 1). 0 outward service calls were retried. 
```

Add the ability to aggregate info about output requests.

---

.travis.yml
Package.resolved
Package.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithoutOutput.swift

*Description of changes:* Add initial async/await support.
1. Following the approach of swift-nio, add these to an underscored package.
2. Front the existing `executeAsEventLoopFuture*` functions.
3. Copies the `EventLoopFuture` async bridge from swift-nio until it is available in a tagged release.

Add initial async/await support.

---

Sources/SmokeHTTPClient/MockCoreInvocationReporting.swift

*Issue #, if available:* #83
*Description of changes:* Delegate to the StandardHTTPClientCoreInvocationReporting initializer in the MockCoreInvocationReporting initializer. Avoids having to duplicate default-value logic between the two initializers.

Delegate to base initializer in the MockCoreInvocationReporting initializer.

---

.travis.yml
Package.resolved
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithOutput.swift
Sources/_SmokeHTTPClientConcurrency/HTTPOperationsClient+executeWithoutOutput.swift

*Description of changes:* Fix compilation under 5.5 and Apple platforms.
Added `@available` annotation as required for swift-nio experimental API[1]
[1] https://github.com/apple/swift-nio/blob/main/Sources/_NIOConcurrency/AsyncAwaitSupport.swift#L21

Fix compilation under 5.5 and Apple platforms.

---

Package.resolved
Sources/SmokeHTTPClient/HTTPClientDelegate.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* 
1. Remove use of deprecated swift-nio API. Walked through the swift-nio code to ensure this code path is equivalent. 
2. Make HTTPClientError.connectTimeout and HTTPClientError.tlsHandshakeTimeout retriable errors

Make connectTimeout and tlsHandshakeTimeout retriable errors

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Don't double wrap errors. If an error from created from the http response, it would be wrapped in the appropriate SmokeHTTPClient.HTTPClientError by the `flatMapThrowing` handler (which is desired and was happening previously to #89) and then wrapped in a 500 SmokeHTTPClient.HTTPClientError by the `flatMapErrorThrowing` handler (which didn't happen previously to #89). This change avoid the second wrapping.

Don't double wrap errors.

---

.travis.yml
Package.resolved
Package.swift
README.md
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
Sources/_SmokeHTTPClientConcurrency/Export.swift

1. Update CI and README for Swift 5.5
2. Move async function APIs into SmokeHTTPClient
3. Re-export SmokeHTTPClient as _SmokeHTTPClientConcurrency to avoid breaking anyone who imported the under-scored package.
4. Update `swift-nio` (also swift-nio-ssl and async-http-client based on advice from @fabianfett) dependency and remove `_NIOConcurrency` imports as they are no longer required.

Final async await support

---

.github/workflows/swift.yml
Package.resolved
Package.swift
README.md
Sources/SmokeHTTPClient/HTTPClientRetryConfiguration.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift

1. Remove @available annotation from async APIs, increase the requirement for non Linux platforms to the upcoming 5.5.2 (which will backport async support to the earlier Apple OSs).
2. Remove Swift 5.2 from CI checks as it has dropped out of its support window.

Remove @available annotation from async APIs.

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Allow retries on HTTPClientError.getConnectionFromPoolTimeout.

Allow retries on HTTPClientError.getConnectionFromPoolTimeout.

---

Package.resolved
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

1. Add async shutdown method for HTTPOperationsClient.
2. Rename existing `close()` method to `syncShutdown` to make its behaviour is clear, deprecating the old method name.

Add async shutdown method for HTTPOperationsClient.

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

Use the timeout value provided to `HTTPOperationsClient` as both the read timeout and the connect timeout of the wrapped `HTTPClient`. Without this change, the HTTP client uses 10 seconds as the connect timeout. This ensures that client calls will return after at most `timeoutValue` (provided `timeoutValue` is smaller than 10).

Set HTTPClient connect timeout to the same value as read timeout

---

Package.resolved
Sources/SmokeHTTPClient/HTTPClientCoreInvocationReporting.swift

*Description of changes:* Extract invocation attributes into separate protocol. Will allow a convenience initializer on clients that accept an instance of this protocol. For example `SmokeServerInvocationReporting` from smoke-framework can be made to conform to this protocol and directly passed to this new convenience initializer.

Extract invocation attributes into separate protocol.

---

Sources/SmokeHTTPClient/HTTPClientInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPClientReportingConfiguration.swift

Move SmokeAWSClientReportingConfiguration as HTTPClientReportingConfiguration from smoke-aws.

Move SmokeAWSClientReportingConfiguration from smoke-aws

---

Sources/SmokeHTTPClient/HTTPClientCoreInvocationReporting.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift
Sources/SmokeHTTPClient/RetriableOutwardsRequestLatencyAggregator.swift

*Description of changes:* Move delegating to the EventLoopFuture APIs closer to the async-http-client call when the Swift Concurrency APIs are called. This will mean retries and response decoding will occur on Swift Concurrency threads.

Retry and decode on Swift Concurrency threads.

---

.github/workflows/swift.yml
Sources/SmokeHTTPClient/HTTPOperationsClient.swift
Sources/SmokeHTTPClient/OffTaskAsyncExecutor.swift

*Description of changes:* For Swift-Concurrency-based APIs, moves the work for serialising and deserialising the request and response bodies from the cooperative thread pool (which could become contended with large request or response bodies due to the limited number of threads in this pool) and onto threads managed by the global dispatch queue itself (which can expand as required). This reduces contention for the cooperative thread pool under these circumstances and provides more stable worse-case latencies.

Off task async executor

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Don't assume an error thrown by clientDelegate.getResponseError is a client error. Use the status code from the response.

Don't assume an error thrown by clientDelegate.getResponseError is a client error.

---

Sources/SmokeHTTPClient/HTTPClientInvocationContext.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

1. Decorate request logger with endpoint and operation; adds "outgoingEndpoint" and "outgoingOperation" as metadata on the logger.

Decorate request logger with endpoint and operation.

---

Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

During outgoing requests, if the endpoint path contains tokens, the `outgoingEndpoint` log decoration would contain the unresolved tokens (ex. `"https://s3.us-west-2.amazonaws.com:443/%7BBucket%7D/%7BKey+%7D"`). This change ensure that the log is decorated with the encoded version of the endpoint path. 

Encode the endpoint path prior to decorating the log context

---

.github/workflows/swift.yml
README.md

*Description of changes:* Add CI for Swift 5.8, drop 5.5.

Add CI for Swift 5.8, drop 5.5.

---

Package.resolved
Package.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Integrated as described [here](https://github.com/apple/swift-distributed-tracing/blob/main/Sources/Tracing/Docs.docc/Guides/InstrumentYourLibrary.md). Verified the traceId is propagated into the request headers as expected.

Integrate apple/swift-distributed-tracing.

---

Sources/SmokeHTTPClient/HTTPError.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Correctly throw HTTPError.unauthorized when the forbidden error code is returned. If possible will decode the response to return the message returned.

Correctly throw HTTPError.unauthorized

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Ensure the serviceContext is always injected into the outgoing request headers.

Ensure the serviceContext is always injected into the outgoing request

---

.github/workflows/codeql.yml
.github/workflows/swift.yml
Package.swift
README.md
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift

*Description of changes:* Add special handling for connection issue retries. Don't count these connection issues towards the retry count configured for the client and don't use exponential backoff. This will shorten the time the client waits on this class of failures.

Add special handling for connection issue retries.

---

Package.swift
Sources/SmokeHTTPClient/HTTPError.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient.swift

Wrap any http failures that we want to treat specially as transient connection issues in `HTTPError.connectionFailure`, allowing the retry logic to easily identify this class of failure and apply custom retry behaviour.

Identify connection failures so they can be retried uniformly.

---

Sources/SmokeHTTPClient/HTTPOperationsClient.swift

*Description of changes:* Treat AsyncHTTPClient.HTTPClientError.cancelled as a connection failure so it gets retried.

Treat AsyncHTTPClient.HTTPClientError.cancelled as a connection failure.

---

Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift

HTTP errors detected as aborted attempts are retried very quickly (2 ms), without exponential backoff. When those errors are caused by connection issues that are transient, but still take more than 10 ms to resolve, calls will fail. With this change, we would transition to using the regular retry loop (with exponential backoff) after the retry-fast attempts are exhausted.

Use regular retry loop when aborted attempts are exhausted

---

Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeAsyncWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient +executeSyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsEventLoopFutureWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeAsyncRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeRetriableWithoutOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithOutput.swift
Sources/SmokeHTTPClient/HTTPOperationsClient+executeWithoutOutput.swift
Sources/SmokeHTTPClient/HttpClientError.swift

Add retry support for error status code 429. This is usually a throttling error status code and can be retried.

Add 429 errors as retryable client errors

---

Package.swift

Add HTTPHeadersCoding dependency in SmokeHTTPClient. SmokeHTTPClient.HTTPClientDelegate depends on HTTPHeadersCoding. Sometimes build fails without explicitly declare this dependency. 

Add HTTPHeadersCoding dependency in SmokeHTTPClient
